package main

var (
	languages = map[string]string{
		"Albanian":   "sq",
		"Catalan":    "ca",
		"Croatian":   "hr",
		"Bulgarian":  "bg",
		"Turkish":    "tr",
		"Greek":      "el",
		"Czech":      "cs",
		"Estonian":   "et",
		"Hungarian":  "hu",
		"Latvian":    "lv",
		"Irish":      "ga",
		"Lithuanian": "lt",
		"Maltese":    "mt",
		"Macedonian": "mk",
		"Slovak":     "sk",
		"Slovenian":  "sl",
		"Ukrainian":  "uk",

		"English":    "en",
		"German":     "du",
		"French":     "fr",
		"Polish":     "pl",
		"Danish":     "da",
		"Spanish":    "es",
		"Portuguese": "pt",
		"Russian":    "ru",
		"Finnish":    "fi",
		"Norwegian":  "no",
		"Icelandic":  "is",
		"Swedish":    "sv",
		"Italian":    "it",
		"Bosnian":    "bs",
		"Serbian":    "sr",
		"Romanian":   "ro",
	}

	locations = map[string]int{
		"Albania":                2008,
		"Andorra":                2020,
		"Austria":                2040,
		"Belgium":                2056,
		"Bosnia and Herzegovina": 2070,
		"Bulgaria":               2100,
		"Croatia":                2191,
		"Cyprus":                 2196,
		"Czechia":                2203,
		"Estonia":                2233,
		"Greece":                 2300,
		"Hungary":                2348,
		"Ireland":                2372,
		"Latvia":                 2428,
		"Liechtenstein":          2438,
		"Lithuania":              2440,
		"Luxembourg":             2442,
		"Malta":                  2470,
		"Moldova":                2498,
		"Monaco":                 2492,
		"Montenegro":             2499,
		"North Macedonia":        2807,
		"San Marino":             2674,
		"Slovakia":               2703,
		"Ukraine":                2804,
		"Vatican City":           2336,
		"Slovenia":               2705,
		"Turkiye":                2792,

		"England":  2826,
		"Germany":  2276,
		"France":   2250,
		"Poland":   2616,
		"Denmark":  2208,
		"Spain":    2724,
		"Portugal": 2620,
		"Russia":   2804,
		"Finland":  2246,
		"Norway":   2578,
		"Iceland":  2352,
		"Sweden":   2752,
		"Italy":    2380,
		"Bosnia":   2070,
		"Serbia":   2688,
		"Romania":  2642,
	}
)
